# Generated by Django 3.0.8 on 2020-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('AD', 'Admin'), ('US', 'User')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('SU', 'Suspended'), ('NV', 'Not Verified')], default='AC', max_length=2),
        ),
    ]
